### ISSUE TITLE
please add DCMIType vocab

### ISSUE THREAD

**Issue by ndushay** [ruby-rdf/rdf-vocab#10]
from http://purl.org/dc/dcmitype/

I think I'm gonna have some delays in getting my contributor release docs together (boss is away for a week or more), or I'd do a pull request.

This should be an easy auto vocab generation.  Might I suggest DCMIType as the class name?

Thanks!

**Comment by gkellogg** [comment]
Should be fairly straightforward. Probably get it out in the next couple of days.

**Comment by ndushay** [comment]
Thank you!
