### ISSUE TITLE
Contribution HOWTO

### ISSUE THREAD

**Issue by anarchivist** [ruby-rdf/rdf-vocab#19]
Hiya - I'm trying to determine how to add a new vocabulary to `rdf/vocab` with the intention of including it. What's the recommended process for doing so?

**Comment by gkellogg** [comment]
Basically, add an entry to lib/rdf/vocab.rb and run the Rake task. Note that it currently requires the vocabulary file to be created first (via touch, say) due to the include issue, which is a bug which needs to be fixed sometime.

Contributions to the README on doing this would be welcome!

**Comment by anarchivist** [comment]
Thanks @gkellogg! I may work on these issues as I have time.
