### ISSUE TITLE
want to update Bibframe vocab but it was hand edited?

### ISSUE THREAD

**Issue by ndushay** [ruby-rdf/rdf-vocab#29]
The bibframe vocab is out of date;  however, there is a commit 15664793 about adding a property by hand to the existing file.   I'm afraid if I follow the instructions using the rake task update vocabs, it will cause more problems than it solves, especially as the hasAccompaniment property is NOT in the bibframe vocab at http://bibframe.org/vocab-list/.  

Plus #26 implies that the rake task will create some additional errors.

What is the best way forward?

**Comment by gkellogg** [comment]
I went to re-load this, to look at the differences, and it seems that we are already using the latest version of this vocabulary.

The process is to run the rake task: `rake lib/rdf/vocab/bibframe.rdf` and then inspect the differences to see if they are expected.

Please close if this satisfies your issue.

**Comment by ndushay** [comment]
yes - it was my bad.  bibframe is a moving target and I was wrong about which thing I was looking at was up to date.
