### ISSUE TITLE
Add DDI-RDF Discovery Vocabulary

### ISSUE THREAD

**Issue by grosscol** [ruby-rdf/rdf-vocab#39]
Description at http://rdf-vocabulary.ddialliance.org/discovery.html
Turtle specification is: https://raw.github.com/linked-statistics/disco-spec/master/discovery.ttl

**Comment by grosscol** [comment]
Went to work on this, but ran into issues when trying to run rake tasks.  `bundle exec rake -T` will yield an error:
```
LoadError: cannot load such file -- rdf/cli/vocab-loader
/home/grosscol/workspace/rdf-vocab/Rakefile:7:in `require'
```

Chalking this up to in flux state of the 2.0 beta.  I'll check back and try generating a vocab again later.

**Comment by gkellogg** [comment]
That's because edge.rb Devon has changes not synced to rdf-vocabulary quite yet. If you fork the 1.99 mains nance branch, and make sure Gemfile does not use github refs, it should work okay. Otherwise, I'll get to it shortly.

**Comment by gkellogg** [comment]
Note that the discovery vocabulary has a minor error: https://github.com/linked-statistics/disco-spec/issues/220. I'll address that in a patch file.

**Comment by gkellogg** [comment]
Also `disco:Representation` class is undefined.
