### ISSUE TITLE
Should SKOS use http://www.w3.org/2008/05/skos namespace?

### ISSUE THREAD

**Issue by jcoyne** [ruby-rdf/rdf-vocab#55]

**Comment by gkellogg** [comment]
The version referenced is “Final Call”. The [2009 version](https://www.w3.org/TR/skos-reference/#namespace-documents) describes the namespace as continuing to be the original 2004 version:

> The SKOS vocabulary is a conceptual resource identified by the namespace URI http://www.w3.org/2004/02/skos/core#. The normative definition of the SKOS vocabulary is found in SKOS Reference (this document).

In any case, changing namespace URIs for established vocabularies is impossible. That’s why FOAF is still at 0.1.

**Comment by jcoyne** [comment]
Thanks for the explanation 👍
